house <- read.table("household_power_consumption.txt", header=TRUE, sep=";")
house$Date<- as.Date(house$Date, format="%d/%m/%Y")
house<- subset(house, Date == "2007-02-01" | Date == "2007-02-02")
house$DateTime <- paste(house$Date, house$Time)
house$DateTime <- strptime(house$DateTime, format="%Y-%m-%d %H:%M:%S")
house$Sub_metering_1 <- as.numeric(as.character(house$Sub_metering_1))
house$Sub_metering_2 <- as.numeric(as.character(house$Sub_metering_2))
house$Sub_metering_3 <- as.numeric(as.character(house$Sub_metering_3))
house$Global_active_power <- as.numeric(as.character(house$Global_active_power))
house$Global_reactive_power <- as.numeric(as.character(house$Global_reactive_power))
house$Voltage <- as.numeric(as.character(house$Voltage))
par(mfrow=c(2,2))
plot(house$DateTime,house$Global_active_power,type="l",ylab="Global Active Power", xlab="", col="black")
plot(house$DateTime,house$Voltage,type="l",ylab="Voltage", xlab="datetime")
with (house,{ 
  plot(DateTime, Sub_metering_1,xlab="", ylab="Energy sub metering", type="l")
  par(new=T)
  plot(DateTime, Sub_metering_2,xlab="",ylab="", col="red", type="l", ylim=range(house1$Sub_metering_1))
  par(new=T)
  plot(DateTime, Sub_metering_3,xlab="",ylab="", col="blue", type="l", ylim=range(house1$Sub_metering_1))
  legend("topright",lty=1, col= c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
  })
plot(house$DateTime,house$Global_reactive_power,type="l",ylab="Global_reactive_power", xlab="datetime")
dev.copy(png, file="plot4.png")
dev.off()
