house <- read.table("household_power_consumption.txt", header=TRUE, sep=";")
house$Date<- as.Date(house$Date, format="%d/%m/%Y")
house<- subset(house, Date == "2007-02-01" | Date == "2007-02-02")
house$Global_active_power <- as.numeric(as.character(house$Global_active_power))
house$DateTime <- paste(house$Date, house$Time)
house$DateTime <- strptime(house$DateTime, format="%Y-%m-%d %H:%M:%S")
plot(house$DateTime,house$Global_active_power,type="l",ylab="Global Active Power (kilowatts)", xlab="")
dev.copy(png, file="plot2.png")
dev.off()
