house <- read.table("household_power_consumption.txt", header=TRUE, sep=";")
house$Date<- as.Date(house$Date, format="%d/%m/%Y")
house<- subset(house, Date == "2007-02-01" | Date == "2007-02-02")
house$DateTime <- paste(house$Date, house$Time)
house$DateTime <- strptime(house$DateTime, format="%Y-%m-%d %H:%M:%S")
house$Sub_metering_1 <- as.numeric(as.character(house$Sub_metering_1))
house$Sub_metering_2 <- as.numeric(as.character(house$Sub_metering_2))
house$Sub_metering_3 <- as.numeric(as.character(house$Sub_metering_3))
plot(house1$DateTime, house1$Sub_metering_1,xlab="", ylab="Energy sub metering", type="l")
par(new=T)
plot(house1$DateTime, house1$Sub_metering_2,xlab="",ylab="", col="red", type="l", ylim=range(house1$Sub_metering_1))
par(new=T)
plot(house1$DateTime, house1$Sub_metering_3,xlab="",ylab="", col="blue", type="l", ylim=range(house1$Sub_metering_1))
legend("topright",lty=1, col= c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png, file="plot3.png")
dev.off()
